language: python
sudo: true
python:
  - "3.5"
  - "3.6"
install:
  - sudo apt-get install libglu1-mesa # pyqt requires .so files
  - pip install tox-travis
  - pip install coveralls
  - pip install flake8
  - pip install flake8-docstrings
script:
  - tox
after_success:
  - coveralls