# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1271, 924)
        MainWindow.setDockNestingEnabled(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitterMain = QtWidgets.QSplitter(self.centralWidget)
        self.splitterMain.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.splitterMain.sizePolicy().hasHeightForWidth())
        self.splitterMain.setSizePolicy(sizePolicy)
        self.splitterMain.setMinimumSize(QtCore.QSize(0, 400))
        self.splitterMain.setSizeIncrement(QtCore.QSize(0, 0))
        self.splitterMain.setBaseSize(QtCore.QSize(0, 0))
        self.splitterMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitterMain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitterMain.setOrientation(QtCore.Qt.Vertical)
        self.splitterMain.setOpaqueResize(True)
        self.splitterMain.setHandleWidth(0)
        self.splitterMain.setChildrenCollapsible(False)
        self.splitterMain.setObjectName("splitterMain")
        self.splitterTop = QtWidgets.QSplitter(self.splitterMain)
        self.splitterTop.setBaseSize(QtCore.QSize(700, 600))
        self.splitterTop.setOrientation(QtCore.Qt.Horizontal)
        self.splitterTop.setHandleWidth(2)
        self.splitterTop.setChildrenCollapsible(False)
        self.splitterTop.setObjectName("splitterTop")
        self.tabWidget = QtWidgets.QTabWidget(self.splitterTop)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Project = QtWidgets.QWidget()
        self.Project.setObjectName("Project")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Project)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.Project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 623, 578))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_requirements = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_requirements.setEnabled(False)
        self.lineEdit_requirements.setObjectName("lineEdit_requirements")
        self.gridLayout.addWidget(self.lineEdit_requirements, 14, 2, 1, 1)
        self.checkBox_requirements = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_requirements.setText("")
        self.checkBox_requirements.setObjectName("checkBox_requirements")
        self.gridLayout.addWidget(self.checkBox_requirements, 14, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_78.setObjectName("label_78")
        self.gridLayout.addWidget(self.label_78, 14, 0, 1, 1)
        self.lineEdit_icon_filename = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_icon_filename.setEnabled(False)
        self.lineEdit_icon_filename.setObjectName("lineEdit_icon_filename")
        self.gridLayout.addWidget(self.lineEdit_icon_filename, 17, 2, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_75.setObjectName("label_75")
        self.gridLayout.addWidget(self.label_75, 17, 0, 1, 1)
        self.checkBox_icon_filename = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_icon_filename.setText("")
        self.checkBox_icon_filename.setObjectName("checkBox_icon_filename")
        self.gridLayout.addWidget(self.checkBox_icon_filename, 17, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_77.setObjectName("label_77")
        self.gridLayout.addWidget(self.label_77, 16, 0, 1, 1)
        self.lineEdit_presplash = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_presplash.setEnabled(False)
        self.lineEdit_presplash.setObjectName("lineEdit_presplash")
        self.gridLayout.addWidget(self.lineEdit_presplash, 16, 2, 1, 1)
        self.checkBox_presplash = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_presplash.setText("")
        self.checkBox_presplash.setObjectName("checkBox_presplash")
        self.gridLayout.addWidget(self.checkBox_presplash, 16, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_76.setObjectName("label_76")
        self.gridLayout.addWidget(self.label_76, 15, 0, 1, 1)
        self.checkBox_garden_requirements = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_garden_requirements.setText("")
        self.checkBox_garden_requirements.setObjectName("checkBox_garden_requirements")
        self.gridLayout.addWidget(self.checkBox_garden_requirements, 15, 1, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.gridLayout.addWidget(self.label_79, 0, 0, 1, 1)
        self.lineEdit_garden_requirements = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_garden_requirements.setEnabled(False)
        self.lineEdit_garden_requirements.setObjectName("lineEdit_garden_requirements")
        self.gridLayout.addWidget(self.lineEdit_garden_requirements, 15, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.checkBox_source_exclude_dirs = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_source_exclude_dirs.setText("")
        self.checkBox_source_exclude_dirs.setObjectName("checkBox_source_exclude_dirs")
        self.gridLayout.addWidget(self.checkBox_source_exclude_dirs, 8, 1, 1, 1)
        self.toolButton_source_dir = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_source_dir.setObjectName("toolButton_source_dir")
        self.gridLayout.addWidget(self.toolButton_source_dir, 7, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.checkBox_source_include_exts = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_source_include_exts.setText("")
        self.checkBox_source_include_exts.setObjectName("checkBox_source_include_exts")
        self.gridLayout.addWidget(self.checkBox_source_include_exts, 9, 1, 1, 1)
        self.lineEdit_source_include_exts = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_source_include_exts.setEnabled(False)
        self.lineEdit_source_include_exts.setObjectName("lineEdit_source_include_exts")
        self.gridLayout.addWidget(self.lineEdit_source_include_exts, 9, 2, 1, 1)
        self.lineEdit_title = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_title.setClearButtonEnabled(False)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.gridLayout.addWidget(self.lineEdit_title, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 2, 2, 1, 1)
        self.lineEdit_source_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_source_dir.setEnabled(True)
        self.lineEdit_source_dir.setObjectName("lineEdit_source_dir")
        self.gridLayout.addWidget(self.lineEdit_source_dir, 7, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.lineEdit_source_exclude_dirs = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_source_exclude_dirs.setEnabled(False)
        self.lineEdit_source_exclude_dirs.setObjectName("lineEdit_source_exclude_dirs")
        self.gridLayout.addWidget(self.lineEdit_source_exclude_dirs, 8, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.checkBox_source_exclude_exts = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_source_exclude_exts.setText("")
        self.checkBox_source_exclude_exts.setObjectName("checkBox_source_exclude_exts")
        self.gridLayout.addWidget(self.checkBox_source_exclude_exts, 10, 1, 1, 1)
        self.lineEdit_domain = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_domain.setObjectName("lineEdit_domain")
        self.gridLayout.addWidget(self.lineEdit_domain, 4, 2, 1, 1)
        self.lineEdit_version = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.gridLayout.addWidget(self.lineEdit_version, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.checkBox_source_exclude_patterns = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_source_exclude_patterns.setText("")
        self.checkBox_source_exclude_patterns.setObjectName("checkBox_source_exclude_patterns")
        self.gridLayout.addWidget(self.checkBox_source_exclude_patterns, 12, 1, 1, 1)
        self.lineEdit_services = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_services.setEnabled(False)
        self.lineEdit_services.setObjectName("lineEdit_services")
        self.gridLayout.addWidget(self.lineEdit_services, 19, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 18, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 12, 0, 1, 1)
        self.lineEdit_source_exclude_patterns = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_source_exclude_patterns.setEnabled(False)
        self.lineEdit_source_exclude_patterns.setObjectName("lineEdit_source_exclude_patterns")
        self.gridLayout.addWidget(self.lineEdit_source_exclude_patterns, 12, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 13, 0, 1, 1)
        self.checkBox_source_include_patterns = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_source_include_patterns.setText("")
        self.checkBox_source_include_patterns.setObjectName("checkBox_source_include_patterns")
        self.gridLayout.addWidget(self.checkBox_source_include_patterns, 11, 1, 1, 1)
        self.checkBox_services = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_services.setText("")
        self.checkBox_services.setObjectName("checkBox_services")
        self.gridLayout.addWidget(self.checkBox_services, 19, 1, 1, 1)
        self.comboBox_orientation = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_orientation.setObjectName("comboBox_orientation")
        self.comboBox_orientation.addItem("")
        self.comboBox_orientation.addItem("")
        self.comboBox_orientation.addItem("")
        self.gridLayout.addWidget(self.comboBox_orientation, 18, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 19, 0, 1, 1)
        self.lineEdit_source_exclude_exts = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_source_exclude_exts.setEnabled(False)
        self.lineEdit_source_exclude_exts.setObjectName("lineEdit_source_exclude_exts")
        self.gridLayout.addWidget(self.lineEdit_source_exclude_exts, 10, 2, 1, 1)
        self.lineEdit_source_include_patterns = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_source_include_patterns.setEnabled(False)
        self.lineEdit_source_include_patterns.setObjectName("lineEdit_source_include_patterns")
        self.gridLayout.addWidget(self.lineEdit_source_include_patterns, 11, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 20, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.Project, "")
        self.tabProject = QtWidgets.QWidget()
        self.tabProject.setEnabled(True)
        self.tabProject.setObjectName("tabProject")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tabProject)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tabProject)
        self.scrollArea_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 644, 506))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_64.setObjectName("label_64")
        self.gridLayout_4.addWidget(self.label_64, 0, 0, 1, 1)
        self.lineEdit_bin_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEdit_bin_dir.setEnabled(False)
        self.lineEdit_bin_dir.setObjectName("lineEdit_bin_dir")
        self.gridLayout_4.addWidget(self.lineEdit_bin_dir, 1, 2, 1, 1)
        self.checkBox_build_dir = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_build_dir.setText("")
        self.checkBox_build_dir.setObjectName("checkBox_build_dir")
        self.gridLayout_4.addWidget(self.checkBox_build_dir, 0, 1, 1, 1)
        self.checkBox_bin_dir = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_bin_dir.setText("")
        self.checkBox_bin_dir.setObjectName("checkBox_bin_dir")
        self.gridLayout_4.addWidget(self.checkBox_bin_dir, 1, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_65.setObjectName("label_65")
        self.gridLayout_4.addWidget(self.label_65, 1, 0, 1, 1)
        self.lineEdit_build_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEdit_build_dir.setEnabled(False)
        self.lineEdit_build_dir.setObjectName("lineEdit_build_dir")
        self.gridLayout_4.addWidget(self.lineEdit_build_dir, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 2, 1, 1)
        self.toolButton_build_dir = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButton_build_dir.setObjectName("toolButton_build_dir")
        self.gridLayout_4.addWidget(self.toolButton_build_dir, 0, 3, 1, 1)
        self.toolButton_bin_dir = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButton_bin_dir.setObjectName("toolButton_bin_dir")
        self.gridLayout_4.addWidget(self.toolButton_bin_dir, 1, 3, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_7.addWidget(self.scrollArea_6)
        self.tabWidget.addTab(self.tabProject, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitterTop)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabAndroid = QtWidgets.QWidget()
        self.tabAndroid.setObjectName("tabAndroid")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabAndroid)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabAndroid)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 591, 506))
        self.scrollAreaWidgetContents_2.setAutoFillBackground(True)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.lineEdit2_android_minapi = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit2_android_minapi.setObjectName("lineEdit2_android_minapi")
        self.gridLayout_2.addWidget(self.lineEdit2_android_minapi, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 9, 0, 1, 1)
        self.checkBox_android_ant_path = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_android_ant_path.setText("")
        self.checkBox_android_ant_path.setObjectName("checkBox_android_ant_path")
        self.gridLayout_2.addWidget(self.checkBox_android_ant_path, 9, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 1, 0, 1, 1)
        self.lineEdit_android_ant_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_android_ant_path.setEnabled(False)
        self.lineEdit_android_ant_path.setText("")
        self.lineEdit_android_ant_path.setObjectName("lineEdit_android_ant_path")
        self.gridLayout_2.addWidget(self.lineEdit_android_ant_path, 9, 2, 1, 1)
        self.toolButton_android_ant_path = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton_android_ant_path.setObjectName("toolButton_android_ant_path")
        self.gridLayout_2.addWidget(self.toolButton_android_ant_path, 9, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 1)
        self.comboBox_android_arch = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_android_arch.setObjectName("comboBox_android_arch")
        self.comboBox_android_arch.addItem("")
        self.comboBox_android_arch.addItem("")
        self.comboBox_android_arch.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_android_arch, 0, 2, 1, 1)
        self.lineEdit2_android_api = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit2_android_api.setObjectName("lineEdit2_android_api")
        self.gridLayout_2.addWidget(self.lineEdit2_android_api, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 15, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 17, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 16, 0, 1, 1)
        self.toolButton_android_permissions = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton_android_permissions.setObjectName("toolButton_android_permissions")
        self.gridLayout_2.addWidget(self.toolButton_android_permissions, 17, 3, 1, 1)
        self.checkBox_android_presplash_color = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_android_presplash_color.setText("")
        self.checkBox_android_presplash_color.setObjectName("checkBox_android_presplash_color")
        self.gridLayout_2.addWidget(self.checkBox_android_presplash_color, 18, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 18, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 0, 1, 1)
        self.checkBox2_fullscreen = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox2_fullscreen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox2_fullscreen.setText("")
        self.checkBox2_fullscreen.setObjectName("checkBox2_fullscreen")
        self.gridLayout_2.addWidget(self.checkBox2_fullscreen, 16, 2, 1, 1)
        self.comboBox_android_presplash_color = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_android_presplash_color.setEnabled(False)
        self.comboBox_android_presplash_color.setObjectName("comboBox_android_presplash_color")
        self.gridLayout_2.addWidget(self.comboBox_android_presplash_color, 18, 2, 1, 1)
        self.toolButton_android_presplash_color = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton_android_presplash_color.setObjectName("toolButton_android_presplash_color")
        self.gridLayout_2.addWidget(self.toolButton_android_presplash_color, 18, 3, 1, 1)
        self.checkBox2_android_private_storage = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox2_android_private_storage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox2_android_private_storage.setText("")
        self.checkBox2_android_private_storage.setObjectName("checkBox2_android_private_storage")
        self.gridLayout_2.addWidget(self.checkBox2_android_private_storage, 19, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 19, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 20, 0, 1, 1)
        self.checkBox2_android_wakelock = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox2_android_wakelock.setText("")
        self.checkBox2_android_wakelock.setObjectName("checkBox2_android_wakelock")
        self.gridLayout_2.addWidget(self.checkBox2_android_wakelock, 20, 2, 1, 1)
        self.lineEdit_android_permissions = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_android_permissions.setObjectName("lineEdit_android_permissions")
        self.gridLayout_2.addWidget(self.lineEdit_android_permissions, 17, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(103, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 21, 0, 1, 1)
        self.checkBox2_android_skip_update = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox2_android_skip_update.setText("")
        self.checkBox2_android_skip_update.setObjectName("checkBox2_android_skip_update")
        self.gridLayout_2.addWidget(self.checkBox2_android_skip_update, 6, 2, 1, 1)
        self.toolButton_android_sdk_path = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton_android_sdk_path.setObjectName("toolButton_android_sdk_path")
        self.gridLayout_2.addWidget(self.toolButton_android_sdk_path, 5, 3, 1, 1)
        self.checkBox_android_sdk_path = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_android_sdk_path.setText("")
        self.checkBox_android_sdk_path.setObjectName("checkBox_android_sdk_path")
        self.gridLayout_2.addWidget(self.checkBox_android_sdk_path, 5, 1, 1, 1)
        self.lineEdit_android_sdk_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_android_sdk_path.setEnabled(False)
        self.lineEdit_android_sdk_path.setText("")
        self.lineEdit_android_sdk_path.setObjectName("lineEdit_android_sdk_path")
        self.gridLayout_2.addWidget(self.lineEdit_android_sdk_path, 5, 2, 1, 1)
        self.lineEdit2_android_sdk = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit2_android_sdk.setObjectName("lineEdit2_android_sdk")
        self.gridLayout_2.addWidget(self.lineEdit2_android_sdk, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setToolTip("")
        self.label_17.setStatusTip("")
        self.label_17.setAccessibleName("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 8, 0, 1, 1)
        self.lineEdit2_android_ndk = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit2_android_ndk.setObjectName("lineEdit2_android_ndk")
        self.gridLayout_2.addWidget(self.lineEdit2_android_ndk, 7, 2, 1, 1)
        self.checkBox_android_ndk_path = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_android_ndk_path.setText("")
        self.checkBox_android_ndk_path.setObjectName("checkBox_android_ndk_path")
        self.gridLayout_2.addWidget(self.checkBox_android_ndk_path, 8, 1, 1, 1)
        self.lineEdit_android_ndk_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_android_ndk_path.setEnabled(False)
        self.lineEdit_android_ndk_path.setStatusTip("")
        self.lineEdit_android_ndk_path.setText("")
        self.lineEdit_android_ndk_path.setObjectName("lineEdit_android_ndk_path")
        self.gridLayout_2.addWidget(self.lineEdit_android_ndk_path, 8, 2, 1, 1)
        self.toolButton_android_ndk_path = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton_android_ndk_path.setObjectName("toolButton_android_ndk_path")
        self.gridLayout_2.addWidget(self.toolButton_android_ndk_path, 8, 3, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.tabWidget_2.addTab(self.tabAndroid, "")
        self.tabAndroid2 = QtWidgets.QWidget()
        self.tabAndroid2.setObjectName("tabAndroid2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabAndroid2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tabAndroid2)
        self.scrollArea_3.setEnabled(True)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 570, 765))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_android_jars = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_jars.setText("")
        self.checkBox_android_jars.setObjectName("checkBox_android_jars")
        self.gridLayout_3.addWidget(self.checkBox_android_jars, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 0, 1, 1)
        self.checkBox_android_add_aars = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_aars.setText("")
        self.checkBox_android_add_aars.setObjectName("checkBox_android_add_aars")
        self.gridLayout_3.addWidget(self.checkBox_android_add_aars, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit_android_jars = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_jars.setEnabled(False)
        self.lineEdit_android_jars.setObjectName("lineEdit_android_jars")
        self.gridLayout_3.addWidget(self.lineEdit_android_jars, 1, 2, 1, 1)
        self.lineEdit_android_add_aars = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_aars.setEnabled(False)
        self.lineEdit_android_add_aars.setObjectName("lineEdit_android_add_aars")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_aars, 2, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 0, 1, 1)
        self.checkBox_android_entrypoint = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_entrypoint.setText("")
        self.checkBox_android_entrypoint.setObjectName("checkBox_android_entrypoint")
        self.gridLayout_3.addWidget(self.checkBox_android_entrypoint, 0, 1, 1, 1)
        self.lineEdit_android_entrypoint = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_entrypoint.setEnabled(False)
        self.lineEdit_android_entrypoint.setObjectName("lineEdit_android_entrypoint")
        self.gridLayout_3.addWidget(self.lineEdit_android_entrypoint, 0, 2, 1, 1)
        self.checkBox_android_manifest_intent_filters = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_manifest_intent_filters.setText("")
        self.checkBox_android_manifest_intent_filters.setObjectName("checkBox_android_manifest_intent_filters")
        self.gridLayout_3.addWidget(self.checkBox_android_manifest_intent_filters, 7, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 8, 0, 1, 1)
        self.checkBox_android_gradle_dependencies = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_gradle_dependencies.setText("")
        self.checkBox_android_gradle_dependencies.setObjectName("checkBox_android_gradle_dependencies")
        self.gridLayout_3.addWidget(self.checkBox_android_gradle_dependencies, 4, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 5, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.checkBox_android_add_java_src = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_java_src.setText("")
        self.checkBox_android_add_java_src.setObjectName("checkBox_android_add_java_src")
        self.gridLayout_3.addWidget(self.checkBox_android_add_java_src, 3, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 7, 0, 1, 1)
        self.lineEdit_android_manifest_intent_filters = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_manifest_intent_filters.setEnabled(False)
        self.lineEdit_android_manifest_intent_filters.setObjectName("lineEdit_android_manifest_intent_filters")
        self.gridLayout_3.addWidget(self.lineEdit_android_manifest_intent_filters, 7, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 4, 0, 1, 1)
        self.lineEdit_android_add_java_src = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_java_src.setEnabled(False)
        self.lineEdit_android_add_java_src.setObjectName("lineEdit_android_add_java_src")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_java_src, 3, 2, 1, 1)
        self.lineEdit_android_gradle_dependencies = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_gradle_dependencies.setEnabled(False)
        self.lineEdit_android_gradle_dependencies.setText("")
        self.lineEdit_android_gradle_dependencies.setObjectName("lineEdit_android_gradle_dependencies")
        self.gridLayout_3.addWidget(self.lineEdit_android_gradle_dependencies, 4, 2, 1, 1)
        self.checkBox_android_add_activites = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_activites.setText("")
        self.checkBox_android_add_activites.setObjectName("checkBox_android_add_activites")
        self.gridLayout_3.addWidget(self.checkBox_android_add_activites, 5, 1, 1, 1)
        self.lineEdit_android_add_activites = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_activites.setEnabled(False)
        self.lineEdit_android_add_activites.setObjectName("lineEdit_android_add_activites")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_activites, 5, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout_3.addWidget(self.label_48, 6, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 22, 0, 1, 1)
        self.checkBox_android_add_libs_mips = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_libs_mips.setText("")
        self.checkBox_android_add_libs_mips.setObjectName("checkBox_android_add_libs_mips")
        self.gridLayout_3.addWidget(self.checkBox_android_add_libs_mips, 22, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 20, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 11, 0, 1, 1)
        self.lineEdit_android_add_libs_mips = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_libs_mips.setEnabled(False)
        self.lineEdit_android_add_libs_mips.setObjectName("lineEdit_android_add_libs_mips")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_libs_mips, 22, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 23, 0, 1, 1)
        self.checkBox_android_manifest_launch_mode = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_manifest_launch_mode.setText("")
        self.checkBox_android_manifest_launch_mode.setObjectName("checkBox_android_manifest_launch_mode")
        self.gridLayout_3.addWidget(self.checkBox_android_manifest_launch_mode, 8, 1, 1, 1)
        self.checkBox_android_library_references = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_library_references.setText("")
        self.checkBox_android_library_references.setObjectName("checkBox_android_library_references")
        self.gridLayout_3.addWidget(self.checkBox_android_library_references, 11, 1, 1, 1)
        self.lineEdit_android_meta_data = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_meta_data.setEnabled(False)
        self.lineEdit_android_meta_data.setObjectName("lineEdit_android_meta_data")
        self.gridLayout_3.addWidget(self.lineEdit_android_meta_data, 10, 2, 1, 1)
        self.checkBox_android_meta_data = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_meta_data.setText("")
        self.checkBox_android_meta_data.setObjectName("checkBox_android_meta_data")
        self.gridLayout_3.addWidget(self.checkBox_android_meta_data, 10, 1, 1, 1)
        self.checkBox_android_logcat_filters = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_logcat_filters.setText("")
        self.checkBox_android_logcat_filters.setObjectName("checkBox_android_logcat_filters")
        self.gridLayout_3.addWidget(self.checkBox_android_logcat_filters, 12, 1, 1, 1)
        self.lineEdit_android_manifest_launch_mode = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_manifest_launch_mode.setEnabled(False)
        self.lineEdit_android_manifest_launch_mode.setObjectName("lineEdit_android_manifest_launch_mode")
        self.gridLayout_3.addWidget(self.lineEdit_android_manifest_launch_mode, 8, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 12, 0, 1, 1)
        self.checkBox_android_copy_libs = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_copy_libs.setText("")
        self.checkBox_android_copy_libs.setObjectName("checkBox_android_copy_libs")
        self.gridLayout_3.addWidget(self.checkBox_android_copy_libs, 13, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 18, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 13, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 19, 0, 1, 1)
        self.lineEdit_android_copy_libs = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_copy_libs.setEnabled(False)
        self.lineEdit_android_copy_libs.setObjectName("lineEdit_android_copy_libs")
        self.gridLayout_3.addWidget(self.lineEdit_android_copy_libs, 13, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 9, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_62.setText("")
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 14, 0, 1, 1)
        self.checkBox_android_add_libs_armeabi = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_libs_armeabi.setText("")
        self.checkBox_android_add_libs_armeabi.setObjectName("checkBox_android_add_libs_armeabi")
        self.gridLayout_3.addWidget(self.checkBox_android_add_libs_armeabi, 19, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 10, 0, 1, 1)
        self.checkBox_android_add_libs_armeabi_v7a = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_libs_armeabi_v7a.setText("")
        self.checkBox_android_add_libs_armeabi_v7a.setObjectName("checkBox_android_add_libs_armeabi_v7a")
        self.gridLayout_3.addWidget(self.checkBox_android_add_libs_armeabi_v7a, 20, 1, 1, 1)
        self.lineEdit_android_add_libs_armeabi_v7a = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_libs_armeabi_v7a.setEnabled(False)
        self.lineEdit_android_add_libs_armeabi_v7a.setObjectName("lineEdit_android_add_libs_armeabi_v7a")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_libs_armeabi_v7a, 20, 2, 1, 1)
        self.lineEdit_android_add_libs_armeabi = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_libs_armeabi.setEnabled(False)
        self.lineEdit_android_add_libs_armeabi.setObjectName("lineEdit_android_add_libs_armeabi")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_libs_armeabi, 19, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 21, 0, 1, 1)
        self.checkBox_android_add_libs_x86 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_add_libs_x86.setText("")
        self.checkBox_android_add_libs_x86.setObjectName("checkBox_android_add_libs_x86")
        self.gridLayout_3.addWidget(self.checkBox_android_add_libs_x86, 21, 1, 1, 1)
        self.lineEdit_android_logcat_filters = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_logcat_filters.setEnabled(False)
        self.lineEdit_android_logcat_filters.setObjectName("lineEdit_android_logcat_filters")
        self.gridLayout_3.addWidget(self.lineEdit_android_logcat_filters, 12, 2, 1, 1)
        self.lineEdit_android_add_libs_x86 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_add_libs_x86.setEnabled(False)
        self.lineEdit_android_add_libs_x86.setObjectName("lineEdit_android_add_libs_x86")
        self.gridLayout_3.addWidget(self.lineEdit_android_add_libs_x86, 21, 2, 1, 1)
        self.lineEdit_android_library_references = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_library_references.setEnabled(False)
        self.lineEdit_android_library_references.setObjectName("lineEdit_android_library_references")
        self.gridLayout_3.addWidget(self.lineEdit_android_library_references, 11, 2, 1, 1)
        self.comboBox_android_ouya_category = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.comboBox_android_ouya_category.setObjectName("comboBox_android_ouya_category")
        self.comboBox_android_ouya_category.addItem("")
        self.comboBox_android_ouya_category.addItem("")
        self.comboBox_android_ouya_category.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_android_ouya_category, 25, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 26, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_3.addWidget(self.label_54, 24, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 25, 0, 1, 1)
        self.checkBox_android_ouya_icon_filename = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_ouya_icon_filename.setText("")
        self.checkBox_android_ouya_icon_filename.setObjectName("checkBox_android_ouya_icon_filename")
        self.gridLayout_3.addWidget(self.checkBox_android_ouya_icon_filename, 26, 1, 1, 1)
        self.lineEdit_android_ouya_icon_filename = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_ouya_icon_filename.setEnabled(False)
        self.lineEdit_android_ouya_icon_filename.setObjectName("lineEdit_android_ouya_icon_filename")
        self.gridLayout_3.addWidget(self.lineEdit_android_ouya_icon_filename, 26, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 27, 2, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 16, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 15, 0, 1, 1)
        self.checkBox_android_whitelist = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_whitelist.setText("")
        self.checkBox_android_whitelist.setObjectName("checkBox_android_whitelist")
        self.gridLayout_3.addWidget(self.checkBox_android_whitelist, 15, 1, 1, 1)
        self.checkBox_android_blacklist = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_android_blacklist.setText("")
        self.checkBox_android_blacklist.setObjectName("checkBox_android_blacklist")
        self.gridLayout_3.addWidget(self.checkBox_android_blacklist, 16, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_70.setText("")
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 17, 0, 1, 1)
        self.lineEdit_android_blacklist = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_blacklist.setEnabled(False)
        self.lineEdit_android_blacklist.setObjectName("lineEdit_android_blacklist")
        self.gridLayout_3.addWidget(self.lineEdit_android_blacklist, 16, 2, 1, 1)
        self.lineEdit_android_whitelist = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_android_whitelist.setEnabled(False)
        self.lineEdit_android_whitelist.setObjectName("lineEdit_android_whitelist")
        self.gridLayout_3.addWidget(self.lineEdit_android_whitelist, 15, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.addWidget(self.scrollArea_3)
        self.tabWidget_2.addTab(self.tabAndroid2, "")
        self.tabP4A = QtWidgets.QWidget()
        self.tabP4A.setObjectName("tabP4A")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabP4A)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tabP4A)
        self.scrollArea_4.setEnabled(True)
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 591, 506))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.checkBox_p4a_branch = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_p4a_branch.setText("")
        self.checkBox_p4a_branch.setObjectName("checkBox_p4a_branch")
        self.gridLayout_6.addWidget(self.checkBox_p4a_branch, 0, 1, 1, 1)
        self.lineEdit_p4a_branch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_p4a_branch.setEnabled(False)
        self.lineEdit_p4a_branch.setObjectName("lineEdit_p4a_branch")
        self.gridLayout_6.addWidget(self.lineEdit_p4a_branch, 0, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 4, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 6, 2, 1, 1)
        self.checkBox_p4a_port = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_p4a_port.setText("")
        self.checkBox_p4a_port.setObjectName("checkBox_p4a_port")
        self.gridLayout_6.addWidget(self.checkBox_p4a_port, 5, 1, 1, 1)
        self.checkBox_p4a_bootstrap = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_p4a_bootstrap.setText("")
        self.checkBox_p4a_bootstrap.setObjectName("checkBox_p4a_bootstrap")
        self.gridLayout_6.addWidget(self.checkBox_p4a_bootstrap, 4, 1, 1, 1)
        self.checkBox_p4a_hook = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_p4a_hook.setText("")
        self.checkBox_p4a_hook.setObjectName("checkBox_p4a_hook")
        self.gridLayout_6.addWidget(self.checkBox_p4a_hook, 3, 1, 1, 1)
        self.checkBox_p4a_local_recipes = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_p4a_local_recipes.setText("")
        self.checkBox_p4a_local_recipes.setObjectName("checkBox_p4a_local_recipes")
        self.gridLayout_6.addWidget(self.checkBox_p4a_local_recipes, 2, 1, 1, 1)
        self.checkBox_p4a_source_dir = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_p4a_source_dir.setText("")
        self.checkBox_p4a_source_dir.setObjectName("checkBox_p4a_source_dir")
        self.gridLayout_6.addWidget(self.checkBox_p4a_source_dir, 1, 1, 1, 1)
        self.lineEdit_p4a_port = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_p4a_port.setEnabled(False)
        self.lineEdit_p4a_port.setObjectName("lineEdit_p4a_port")
        self.gridLayout_6.addWidget(self.lineEdit_p4a_port, 5, 2, 1, 1)
        self.lineEdit_p4a_bootstrap = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_p4a_bootstrap.setEnabled(False)
        self.lineEdit_p4a_bootstrap.setObjectName("lineEdit_p4a_bootstrap")
        self.gridLayout_6.addWidget(self.lineEdit_p4a_bootstrap, 4, 2, 1, 1)
        self.lineEdit_p4a_hook = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_p4a_hook.setEnabled(False)
        self.lineEdit_p4a_hook.setObjectName("lineEdit_p4a_hook")
        self.gridLayout_6.addWidget(self.lineEdit_p4a_hook, 3, 2, 1, 1)
        self.lineEdit_p4a_local_recipes = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_p4a_local_recipes.setEnabled(False)
        self.lineEdit_p4a_local_recipes.setObjectName("lineEdit_p4a_local_recipes")
        self.gridLayout_6.addWidget(self.lineEdit_p4a_local_recipes, 2, 2, 1, 1)
        self.lineEdit_p4a_source_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_p4a_source_dir.setEnabled(False)
        self.lineEdit_p4a_source_dir.setObjectName("lineEdit_p4a_source_dir")
        self.gridLayout_6.addWidget(self.lineEdit_p4a_source_dir, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout.addWidget(self.scrollArea_4)
        self.tabWidget_2.addTab(self.tabP4A, "")
        self.tabIOS = QtWidgets.QWidget()
        self.tabIOS.setObjectName("tabIOS")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabIOS)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tabIOS)
        self.scrollArea_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 591, 506))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_66.setObjectName("label_66")
        self.gridLayout_5.addWidget(self.label_66, 1, 0, 1, 1)
        self.checkBox_ios_codesign_debug = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_ios_codesign_debug.setText("")
        self.checkBox_ios_codesign_debug.setObjectName("checkBox_ios_codesign_debug")
        self.gridLayout_5.addWidget(self.checkBox_ios_codesign_debug, 1, 1, 1, 1)
        self.lineEdit_ios_codesign_debug = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_ios_codesign_debug.setEnabled(False)
        self.lineEdit_ios_codesign_debug.setObjectName("lineEdit_ios_codesign_debug")
        self.gridLayout_5.addWidget(self.lineEdit_ios_codesign_debug, 1, 2, 1, 1)
        self.checkBox_ios_kivy_ios_dir = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_ios_kivy_ios_dir.setText("")
        self.checkBox_ios_kivy_ios_dir.setObjectName("checkBox_ios_kivy_ios_dir")
        self.gridLayout_5.addWidget(self.checkBox_ios_kivy_ios_dir, 0, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 0, 0, 1, 1)
        self.lineEdit_ios_kivy_ios_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_ios_kivy_ios_dir.setEnabled(False)
        self.lineEdit_ios_kivy_ios_dir.setObjectName("lineEdit_ios_kivy_ios_dir")
        self.gridLayout_5.addWidget(self.lineEdit_ios_kivy_ios_dir, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 3, 2, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_67.setObjectName("label_67")
        self.gridLayout_5.addWidget(self.label_67, 2, 0, 1, 1)
        self.checkBox_ios_codesign_release = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_ios_codesign_release.setText("")
        self.checkBox_ios_codesign_release.setObjectName("checkBox_ios_codesign_release")
        self.gridLayout_5.addWidget(self.checkBox_ios_codesign_release, 2, 1, 1, 1)
        self.lineEdit_ios_codesign_release = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEdit_ios_codesign_release.setEnabled(False)
        self.lineEdit_ios_codesign_release.setObjectName("lineEdit_ios_codesign_release")
        self.gridLayout_5.addWidget(self.lineEdit_ios_codesign_release, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_6.addWidget(self.scrollArea_5)
        self.tabWidget_2.addTab(self.tabIOS, "")
        self.tabOSX = QtWidgets.QWidget()
        self.tabOSX.setObjectName("tabOSX")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tabOSX)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tabOSX)
        self.scrollArea_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_7.setLineWidth(0)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 591, 506))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_71.setObjectName("label_71")
        self.gridLayout_7.addWidget(self.label_71, 1, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_72.setObjectName("label_72")
        self.gridLayout_7.addWidget(self.label_72, 2, 0, 1, 1)
        self.spinBox_osx_python_version = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_8)
        self.spinBox_osx_python_version.setMinimum(2)
        self.spinBox_osx_python_version.setProperty("value", 3)
        self.spinBox_osx_python_version.setObjectName("spinBox_osx_python_version")
        self.gridLayout_7.addWidget(self.spinBox_osx_python_version, 1, 2, 1, 1)
        self.lineEdit_osx_kivy_version = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_8)
        self.lineEdit_osx_kivy_version.setEnabled(False)
        self.lineEdit_osx_kivy_version.setObjectName("lineEdit_osx_kivy_version")
        self.gridLayout_7.addWidget(self.lineEdit_osx_kivy_version, 2, 2, 1, 1)
        self.checkBox_osx_kivy_version = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_8)
        self.checkBox_osx_kivy_version.setText("")
        self.checkBox_osx_kivy_version.setObjectName("checkBox_osx_kivy_version")
        self.gridLayout_7.addWidget(self.checkBox_osx_kivy_version, 2, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_73.setObjectName("label_73")
        self.gridLayout_7.addWidget(self.label_73, 0, 0, 1, 1)
        self.lineEdit_author = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_8)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.gridLayout_7.addWidget(self.lineEdit_author, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.horizontalLayout_8.addWidget(self.scrollArea_7)
        self.tabWidget_2.addTab(self.tabOSX, "")
        self.widget = QtWidgets.QWidget(self.splitterMain)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_3)
        self.verticalLayout_5.addWidget(self.splitterMain)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1271, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuSettings.addAction(self.actionSettings)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.checkBox_source_exclude_dirs.toggled['bool'].connect(self.lineEdit_source_exclude_dirs.setEnabled)
        self.checkBox_source_exclude_patterns.toggled['bool'].connect(self.lineEdit_source_exclude_patterns.setEnabled)
        self.checkBox_source_exclude_exts.toggled['bool'].connect(self.lineEdit_source_exclude_exts.setEnabled)
        self.checkBox_source_include_patterns.toggled['bool'].connect(self.lineEdit_source_include_patterns.setEnabled)
        self.checkBox_source_include_exts.toggled['bool'].connect(self.lineEdit_source_include_exts.setEnabled)
        self.checkBox_services.toggled['bool'].connect(self.lineEdit_services.setEnabled)
        self.checkBox_android_ant_path.toggled['bool'].connect(self.lineEdit_android_ant_path.setEnabled)
        self.checkBox_android_ndk_path.toggled['bool'].connect(self.lineEdit_android_ndk_path.setEnabled)
        self.checkBox_android_presplash_color.toggled['bool'].connect(self.comboBox_android_presplash_color.setEnabled)
        self.checkBox_android_sdk_path.toggled['bool'].connect(self.lineEdit_android_sdk_path.setEnabled)
        self.checkBox_requirements.toggled['bool'].connect(self.lineEdit_requirements.setEnabled)
        self.checkBox_garden_requirements.toggled['bool'].connect(self.lineEdit_garden_requirements.setEnabled)
        self.checkBox_presplash.toggled['bool'].connect(self.lineEdit_presplash.setEnabled)
        self.checkBox_icon_filename.toggled['bool'].connect(self.lineEdit_icon_filename.setEnabled)
        self.checkBox_android_ant_path.toggled['bool'].connect(self.lineEdit_android_ant_path.setEnabled)
        self.checkBox_android_entrypoint.toggled['bool'].connect(self.lineEdit_android_entrypoint.setEnabled)
        self.checkBox_android_add_aars.toggled['bool'].connect(self.lineEdit_android_add_aars.setEnabled)
        self.checkBox_android_add_java_src.toggled['bool'].connect(self.lineEdit_android_add_java_src.setEnabled)
        self.checkBox_android_gradle_dependencies.toggled['bool'].connect(self.lineEdit_android_gradle_dependencies.setEnabled)
        self.checkBox_android_add_activites.toggled['bool'].connect(self.lineEdit_android_add_activites.setEnabled)
        self.checkBox_android_manifest_intent_filters.toggled['bool'].connect(self.lineEdit_android_manifest_intent_filters.setEnabled)
        self.checkBox_android_manifest_launch_mode.toggled['bool'].connect(self.lineEdit_android_manifest_launch_mode.setEnabled)
        self.checkBox_android_meta_data.toggled['bool'].connect(self.lineEdit_android_meta_data.setEnabled)
        self.checkBox_android_library_references.toggled['bool'].connect(self.lineEdit_android_library_references.setEnabled)
        self.checkBox_android_logcat_filters.toggled['bool'].connect(self.lineEdit_android_logcat_filters.setEnabled)
        self.checkBox_android_copy_libs.toggled['bool'].connect(self.lineEdit_android_copy_libs.setEnabled)
        self.checkBox_android_whitelist.toggled['bool'].connect(self.lineEdit_android_whitelist.setEnabled)
        self.checkBox_android_blacklist.toggled['bool'].connect(self.lineEdit_android_blacklist.setEnabled)
        self.checkBox_android_add_libs_armeabi.toggled['bool'].connect(self.lineEdit_android_add_libs_armeabi.setEnabled)
        self.checkBox_android_add_libs_armeabi_v7a.toggled['bool'].connect(self.lineEdit_android_add_libs_armeabi_v7a.setEnabled)
        self.checkBox_android_add_libs_x86.toggled['bool'].connect(self.lineEdit_android_add_libs_x86.setEnabled)
        self.checkBox_android_add_libs_mips.toggled['bool'].connect(self.lineEdit_android_add_libs_mips.setEnabled)
        self.checkBox_android_ouya_icon_filename.toggled['bool'].connect(self.lineEdit_android_ouya_icon_filename.setEnabled)
        self.checkBox_p4a_branch.toggled['bool'].connect(self.lineEdit_p4a_branch.setEnabled)
        self.checkBox_p4a_source_dir.toggled['bool'].connect(self.lineEdit_p4a_source_dir.setEnabled)
        self.checkBox_p4a_local_recipes.toggled['bool'].connect(self.lineEdit_p4a_local_recipes.setEnabled)
        self.checkBox_p4a_hook.toggled['bool'].connect(self.lineEdit_p4a_hook.setEnabled)
        self.checkBox_p4a_bootstrap.toggled['bool'].connect(self.lineEdit_p4a_bootstrap.setEnabled)
        self.checkBox_p4a_port.toggled['bool'].connect(self.lineEdit_p4a_port.setEnabled)
        self.checkBox_ios_kivy_ios_dir.toggled['bool'].connect(self.lineEdit_ios_kivy_ios_dir.setEnabled)
        self.checkBox_ios_codesign_debug.toggled['bool'].connect(self.lineEdit_ios_codesign_debug.setEnabled)
        self.checkBox_ios_codesign_release.toggled['bool'].connect(self.lineEdit_ios_codesign_release.setEnabled)
        self.checkBox_osx_kivy_version.toggled['bool'].connect(self.lineEdit_osx_kivy_version.setEnabled)
        self.checkBox_build_dir.toggled['bool'].connect(self.lineEdit_build_dir.setEnabled)
        self.checkBox_bin_dir.toggled['bool'].connect(self.lineEdit_bin_dir.setEnabled)
        self.menuBar.triggered['QAction*'].connect(MainWindow.onMenubar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_requirements.setText(_translate("MainWindow", "sqlite3,kivy"))
        self.label_78.setText(_translate("MainWindow", "Application Requirements:"))
        self.lineEdit_icon_filename.setText(_translate("MainWindow", "%(source.dir)s/data/icon.png"))
        self.label_75.setText(_translate("MainWindow", "Application Icon:"))
        self.label_77.setText(_translate("MainWindow", "Presplash Image:"))
        self.lineEdit_presplash.setToolTip(_translate("MainWindow", "Presplash of the application"))
        self.lineEdit_presplash.setText(_translate("MainWindow", "%(source.dir)s/data/presplash.png"))
        self.label_76.setText(_translate("MainWindow", "Garden Requirements:"))
        self.label_79.setText(_translate("MainWindow", "Application"))
        self.label_5.setText(_translate("MainWindow", "Source Dir:"))
        self.toolButton_source_dir.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Domain:"))
        self.label_9.setText(_translate("MainWindow", "Source Exclude Dirs:"))
        self.lineEdit_source_include_exts.setToolTip(_translate("MainWindow", "# (list) Source files to include (let empty to include all the files)"))
        self.lineEdit_source_include_exts.setText(_translate("MainWindow", "py,png,jpg,kv,atlas"))
        self.lineEdit_title.setText(_translate("MainWindow", "AppTitle"))
        self.label_2.setText(_translate("MainWindow", "Package Name:"))
        self.lineEdit_name.setText(_translate("MainWindow", "myapp"))
        self.lineEdit_source_dir.setToolTip(_translate("MainWindow", "Source code where the main.py"))
        self.lineEdit_source_dir.setText(_translate("MainWindow", "."))
        self.label_8.setText(_translate("MainWindow", "Source Exclude Exts:"))
        self.lineEdit_source_exclude_dirs.setToolTip(_translate("MainWindow", "List of directory to exclude (let empty to not exclude anything)"))
        self.lineEdit_source_exclude_dirs.setText(_translate("MainWindow", "tests,bin"))
        self.label_6.setText(_translate("MainWindow", "Source Include Exts:"))
        self.label_3.setText(_translate("MainWindow", "Version:"))
        self.lineEdit_domain.setToolTip(_translate("MainWindow", "# (str) Package domain (needed for android/ios packaging)"))
        self.lineEdit_domain.setText(_translate("MainWindow", "org.test"))
        self.lineEdit_version.setText(_translate("MainWindow", "0.1"))
        self.label.setText(_translate("MainWindow", "Title:"))
        self.lineEdit_services.setToolTip(_translate("MainWindow", "List of service to declare"))
        self.lineEdit_services.setText(_translate("MainWindow", "NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY"))
        self.label_11.setText(_translate("MainWindow", "Orientation:"))
        self.label_10.setText(_translate("MainWindow", "Source Exclude Patterns:"))
        self.lineEdit_source_exclude_patterns.setToolTip(_translate("MainWindow", "# (list) List of exclusions using pattern matching"))
        self.lineEdit_source_exclude_patterns.setText(_translate("MainWindow", "license,images/*/*.jpg"))
        self.comboBox_orientation.setToolTip(_translate("MainWindow", "# (str) Supported orientation (one of landscape, portrait or all)"))
        self.comboBox_orientation.setItemText(0, _translate("MainWindow", "Landscape"))
        self.comboBox_orientation.setItemText(1, _translate("MainWindow", "Portrait"))
        self.comboBox_orientation.setItemText(2, _translate("MainWindow", "All"))
        self.label_26.setText(_translate("MainWindow", "Services:"))
        self.lineEdit_source_exclude_exts.setToolTip(_translate("MainWindow", "# (list) Source files to exclude (let empty to not exclude anything)"))
        self.lineEdit_source_exclude_exts.setText(_translate("MainWindow", "spec"))
        self.lineEdit_source_include_patterns.setToolTip(_translate("MainWindow", "# (list) List of inclusions using pattern matching"))
        self.lineEdit_source_include_patterns.setText(_translate("MainWindow", "assets/*,images/*.png"))
        self.label_7.setText(_translate("MainWindow", "Source Include Patterns:"))
        self.label_31.setText(_translate("MainWindow", "Source"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Project), _translate("MainWindow", "Project"))
        self.label_64.setText(_translate("MainWindow", "Build Dir:"))
        self.lineEdit_bin_dir.setToolTip(_translate("MainWindow", "(str) Path to build output (i.e. .apk, .ipa) storage"))
        self.lineEdit_bin_dir.setText(_translate("MainWindow", "./bin"))
        self.label_65.setText(_translate("MainWindow", "Bin Dir:"))
        self.lineEdit_build_dir.setToolTip(_translate("MainWindow", "(str) Path to build artifact storage, absolute or relative to spec file"))
        self.lineEdit_build_dir.setText(_translate("MainWindow", "./.buildozer"))
        self.toolButton_build_dir.setText(_translate("MainWindow", "..."))
        self.toolButton_bin_dir.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProject), _translate("MainWindow", "Build"))
        self.label_21.setText(_translate("MainWindow", "Android Min API:"))
        self.lineEdit2_android_minapi.setToolTip(_translate("MainWindow", "Minimum API required"))
        self.lineEdit2_android_minapi.setText(_translate("MainWindow", "19"))
        self.label_13.setText(_translate("MainWindow", "Android ANT Path:"))
        self.label_20.setText(_translate("MainWindow", "Android API:"))
        self.lineEdit_android_ant_path.setToolTip(_translate("MainWindow", "Android ANT directory (if empty, it will be automatically downloaded.)"))
        self.toolButton_android_ant_path.setText(_translate("MainWindow", "..."))
        self.label_25.setText(_translate("MainWindow", "Android Arch:"))
        self.comboBox_android_arch.setToolTip(_translate("MainWindow", "The Android arch to build for"))
        self.comboBox_android_arch.setItemText(0, _translate("MainWindow", "armeabi-v7a"))
        self.comboBox_android_arch.setItemText(1, _translate("MainWindow", "arm64-v8a"))
        self.comboBox_android_arch.setItemText(2, _translate("MainWindow", "x86"))
        self.lineEdit2_android_api.setToolTip(_translate("MainWindow", " Android API to use"))
        self.lineEdit2_android_api.setText(_translate("MainWindow", "19"))
        self.label_22.setText(_translate("MainWindow", "Android SDK:"))
        self.label_16.setText(_translate("MainWindow", "Skip SDK Update:"))
        self.label_19.setText(_translate("MainWindow", "Android NDK:"))
        self.label_23.setText(_translate("MainWindow", "Permissions:"))
        self.label_12.setText(_translate("MainWindow", "Fullscreen:"))
        self.toolButton_android_permissions.setText(_translate("MainWindow", "..."))
        self.label_14.setText(_translate("MainWindow", "Presplash Color:"))
        self.label_18.setText(_translate("MainWindow", "Android SDK Path:"))
        self.toolButton_android_presplash_color.setText(_translate("MainWindow", "..."))
        self.checkBox2_android_private_storage.setToolTip(_translate("MainWindow", "(bool) Use --private data storage (True) or --dir public storage (False)"))
        self.label_24.setText(_translate("MainWindow", "Private Storage:"))
        self.label_58.setText(_translate("MainWindow", "Wakelock:"))
        self.checkBox2_android_wakelock.setToolTip(_translate("MainWindow", "# (bool) Indicate whether the screen should stay on\n"
"# Don\'t forget to add the WAKE_LOCK permission if you set this to True"))
        self.lineEdit_android_permissions.setText(_translate("MainWindow", "INTERNET"))
        self.checkBox2_android_skip_update.setToolTip(_translate("MainWindow", "If checked, then skip trying to update the Android sdk"))
        self.toolButton_android_sdk_path.setText(_translate("MainWindow", "..."))
        self.lineEdit_android_sdk_path.setToolTip(_translate("MainWindow", "Android SDK directory (if empty, it will be automatically downloaded.)"))
        self.lineEdit2_android_sdk.setText(_translate("MainWindow", "20"))
        self.label_17.setText(_translate("MainWindow", "Android NDK Path:"))
        self.lineEdit2_android_ndk.setToolTip(_translate("MainWindow", "Android NDK version to use"))
        self.lineEdit2_android_ndk.setText(_translate("MainWindow", "9c"))
        self.lineEdit_android_ndk_path.setToolTip(_translate("MainWindow", "Android NDK directory (if empty, it will be automatically downloaded.)"))
        self.toolButton_android_ndk_path.setText(_translate("MainWindow", "..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabAndroid), _translate("MainWindow", "Android"))
        self.label_28.setToolTip(_translate("MainWindow", " # (list) Android AAR archives to add (currently works only with sdl2_gradle\n"
"    # bootstrap)"))
        self.label_28.setText(_translate("MainWindow", "Android AAR Archives:"))
        self.label_15.setText(_translate("MainWindow", "Android Jars:"))
        self.lineEdit_android_jars.setToolTip(_translate("MainWindow", "# (list) List of Java .jar files to add to the libs so that pyjnius can access\n"
"    # their classes. Don\'t add jars that you do not need, since extra jars can slow\n"
"    # down the build process. Allows wildcards matching, for example:\n"
"    # OUYA-ODK/libs/*.jar\n"
"    #android_add_jars: foo.jar,bar.jar,path/to/more/*.jar"))
        self.lineEdit_android_jars.setText(_translate("MainWindow", "foo.jar,bar.jar,path/to/more/*.jar"))
        self.lineEdit_android_add_aars.setToolTip(_translate("MainWindow", "# (list) Android AAR archives to add (currently works only with sdl2_gradle\n"
"# bootstrap"))
        self.label_33.setText(_translate("MainWindow", "Android Entry Point:"))
        self.lineEdit_android_entrypoint.setToolTip(_translate("MainWindow", "(str) Android entry point, default is ok for Kivy-based app"))
        self.lineEdit_android_entrypoint.setText(_translate("MainWindow", "org.renpy.android.PythonActivity"))
        self.label_57.setText(_translate("MainWindow", "Manifest Launch Mode:"))
        self.label_39.setText(_translate("MainWindow", "Activities (Java classes):"))
        self.label_27.setToolTip(_translate("MainWindow", "# (list) List of Java files to add to the android project (can be java or a\n"
"    # directory containing the files)"))
        self.label_27.setText(_translate("MainWindow", "Java Source:"))
        self.label_56.setText(_translate("MainWindow", "Manifest Intent Filters:"))
        self.lineEdit_android_manifest_intent_filters.setToolTip(_translate("MainWindow", "# (str) XML file to include as an intent filters in <activity> tag"))
        self.label_38.setText(_translate("MainWindow", "Gradle Dependencies:"))
        self.lineEdit_android_add_java_src.setToolTip(_translate("MainWindow", "# (list) List of Java files to add to the android project (can be java or a\n"
"# directory containing the files)"))
        self.lineEdit_android_gradle_dependencies.setToolTip(_translate("MainWindow", "(list) Gradle dependencies to add (currently works only with sdl2_gradle # bootstrap)"))
        self.lineEdit_android_add_activites.setToolTip(_translate("MainWindow", "# (list) Java classes to add as activities to the manifest."))
        self.lineEdit_android_add_activites.setText(_translate("MainWindow", "com.example.ExampleActivity"))
        self.label_53.setText(_translate("MainWindow", "MIPS Libs"))
        self.label_51.setText(_translate("MainWindow", "Armeabi v7a Libs"))
        self.label_61.setText(_translate("MainWindow", "Library References:"))
        self.lineEdit_android_add_libs_mips.setText(_translate("MainWindow", "libs/android-mips/*.so"))
        self.lineEdit_android_meta_data.setToolTip(_translate("MainWindow", "# (list) Android application meta-data to set (key=value format)"))
        self.lineEdit_android_manifest_launch_mode.setToolTip(_translate("MainWindow", "# (str) launchMode to set for the main activity"))
        self.lineEdit_android_manifest_launch_mode.setText(_translate("MainWindow", "standard"))
        self.label_60.setText(_translate("MainWindow", "Logcat Filters:"))
        self.label_37.setToolTip(_translate("MainWindow", "# (list) Android additionnal libraries to copy into libs/armeabi"))
        self.label_37.setText(_translate("MainWindow", "Additional Libraries"))
        self.label_63.setText(_translate("MainWindow", "Copy Libraries:"))
        self.label_50.setText(_translate("MainWindow", "Armeabi Libs"))
        self.lineEdit_android_copy_libs.setToolTip(_translate("MainWindow", "(bool) Copy library instead of making a libpymodules.so"))
        self.label_59.setText(_translate("MainWindow", "Android Meta-data:"))
        self.lineEdit_android_add_libs_armeabi_v7a.setText(_translate("MainWindow", "libs/android-v7/*.so"))
        self.lineEdit_android_add_libs_armeabi.setText(_translate("MainWindow", "libs/android/*.so"))
        self.label_52.setText(_translate("MainWindow", "x86 Libs"))
        self.lineEdit_android_logcat_filters.setToolTip(_translate("MainWindow", "# (str) Android logcat filters to use"))
        self.lineEdit_android_logcat_filters.setText(_translate("MainWindow", "*:S python:D"))
        self.lineEdit_android_add_libs_x86.setText(_translate("MainWindow", "libs/android-x86/*.so"))
        self.lineEdit_android_library_references.setToolTip(_translate("MainWindow", "# (list) Android library project to add (will be added in the\n"
"# project.properties automatically.)"))
        self.comboBox_android_ouya_category.setToolTip(_translate("MainWindow", "# (str) OUYA Console category. Should be one of GAME or APP\n"
"# If you leave this blank, OUYA support will not be enabled"))
        self.comboBox_android_ouya_category.setItemText(0, _translate("MainWindow", "Disabled"))
        self.comboBox_android_ouya_category.setItemText(1, _translate("MainWindow", "APP"))
        self.comboBox_android_ouya_category.setItemText(2, _translate("MainWindow", "GAME"))
        self.label_36.setText(_translate("MainWindow", "Ouya Icon: (732x412 PNG)"))
        self.label_54.setText(_translate("MainWindow", "Ouya"))
        self.label_35.setText(_translate("MainWindow", "Ouya Category:"))
        self.lineEdit_android_ouya_icon_filename.setToolTip(_translate("MainWindow", "# (str) Filename of OUYA Console icon. It must be a 732x412 png image."))
        self.lineEdit_android_ouya_icon_filename.setText(_translate("MainWindow", "%(source.dir)s/data/ouya_icon.png"))
        self.label_68.setText(_translate("MainWindow", "Android Blacklist:"))
        self.label_69.setText(_translate("MainWindow", "Android Whitelist:"))
        self.lineEdit_android_blacklist.setToolTip(_translate("MainWindow", "blacklist file"))
        self.lineEdit_android_whitelist.setToolTip(_translate("MainWindow", "(list) Pattern to whitelist for the whole project"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabAndroid2), _translate("MainWindow", "Android (Advanced)"))
        self.tabP4A.setToolTip(_translate("MainWindow", "Python for android (p4a) specific"))
        self.label_34.setText(_translate("MainWindow", "P4A Branch:"))
        self.lineEdit_p4a_branch.setToolTip(_translate("MainWindow", "(str) python-for-android branch to use, defaults to stable"))
        self.lineEdit_p4a_branch.setText(_translate("MainWindow", "stable"))
        self.label_42.setText(_translate("MainWindow", "P4A Source Dir:"))
        self.label_43.setText(_translate("MainWindow", "P4A Recipes Dir:"))
        self.label_44.setText(_translate("MainWindow", "P4A Hook:"))
        self.label_45.setText(_translate("MainWindow", "P4A Bootstrap:"))
        self.label_46.setText(_translate("MainWindow", "P4A Port:"))
        self.lineEdit_p4a_port.setToolTip(_translate("MainWindow", "(int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)"))
        self.lineEdit_p4a_bootstrap.setToolTip(_translate("MainWindow", "(str) Bootstrap to use for android builds"))
        self.lineEdit_p4a_bootstrap.setText(_translate("MainWindow", "sdl2"))
        self.lineEdit_p4a_hook.setToolTip(_translate("MainWindow", "(str) Filename to the hook for p4a"))
        self.lineEdit_p4a_local_recipes.setToolTip(_translate("MainWindow", "(str) The directory in which python-for-android should look for your own build recipes (if any)"))
        self.lineEdit_p4a_source_dir.setToolTip(_translate("MainWindow", "(str) python-for-android git clone directory (if empty, it will be automatically cloned from github)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabP4A), _translate("MainWindow", "Python-For-Android"))
        self.label_66.setText(_translate("MainWindow", "IOS Codesign Debug:"))
        self.lineEdit_ios_codesign_debug.setToolTip(_translate("MainWindow", "# (str) Name of the certificate to use for signing the debug version\n"
"# Get a list of available identities: buildozer ios list_identities"))
        self.lineEdit_ios_codesign_debug.setText(_translate("MainWindow", "\"iPhone Developer: <lastname> <firstname> (<hexstring>)\""))
        self.label_47.setText(_translate("MainWindow", "IOS Kivy Dir:"))
        self.lineEdit_ios_kivy_ios_dir.setToolTip(_translate("MainWindow", "(str) Path to a custom kivy-ios folder"))
        self.lineEdit_ios_kivy_ios_dir.setText(_translate("MainWindow", "../kivy-ios"))
        self.label_67.setText(_translate("MainWindow", "IOS Codesign Release:"))
        self.lineEdit_ios_codesign_release.setToolTip(_translate("MainWindow", "(str) Name of the certificate to use for signing the release version"))
        self.lineEdit_ios_codesign_release.setText(_translate("MainWindow", "%(ios.codesign.debug)s"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabIOS), _translate("MainWindow", "iOS"))
        self.label_71.setText(_translate("MainWindow", "OSX Python Version:"))
        self.label_72.setText(_translate("MainWindow", "OSX Kivy Version:"))
        self.spinBox_osx_python_version.setToolTip(_translate("MainWindow", "# change the major version of python used by the app"))
        self.lineEdit_osx_kivy_version.setToolTip(_translate("MainWindow", "# Kivy version to use"))
        self.lineEdit_osx_kivy_version.setText(_translate("MainWindow", "1.9.1"))
        self.label_73.setText(_translate("MainWindow", "Author"))
        self.lineEdit_author.setText(_translate("MainWindow", "© Copyright Info"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabOSX), _translate("MainWindow", "OSX"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+P"))

