# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(526, 591)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startIp = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.startIp.setFont(font)
        self.startIp.setEditable(True)
        self.startIp.setCurrentText("192.168.0.0")
        self.startIp.setObjectName("startIp")
        self.horizontalLayout.addWidget(self.startIp)
        self.endIp = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.endIp.setFont(font)
        self.endIp.setEditable(True)
        self.endIp.setCurrentText("192.168.0.255")
        self.endIp.setObjectName("endIp")
        self.horizontalLayout.addWidget(self.endIp)
        self.btnScan = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScan.sizePolicy().hasHeightForWidth())
        self.btnScan.setSizePolicy(sizePolicy)
        self.btnScan.setText("")
        self.btnScan.setObjectName("btnScan")
        self.horizontalLayout.addWidget(self.btnScan)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stringIp = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.stringIp.setFont(font)
        self.stringIp.setEditable(True)
        self.stringIp.setObjectName("stringIp")
        self.horizontalLayout_2.addWidget(self.stringIp)
        self.btnCustomScan = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCustomScan.sizePolicy().hasHeightForWidth())
        self.btnCustomScan.setSizePolicy(sizePolicy)
        self.btnCustomScan.setText("")
        self.btnCustomScan.setObjectName("btnCustomScan")
        self.horizontalLayout_2.addWidget(self.btnCustomScan)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinHostTimeout = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinHostTimeout.setMinimum(-1)
        self.spinHostTimeout.setObjectName("spinHostTimeout")
        self.horizontalLayout_3.addWidget(self.spinHostTimeout)
        self.checkBoxHostname = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxHostname.setObjectName("checkBoxHostname")
        self.horizontalLayout_3.addWidget(self.checkBoxHostname)
        self.checkBoxMac = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxMac.setToolTip("")
        self.checkBoxMac.setObjectName("checkBoxMac")
        self.horizontalLayout_3.addWidget(self.checkBoxMac)
        self.checkBoxManufacturer = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxManufacturer.setObjectName("checkBoxManufacturer")
        self.horizontalLayout_3.addWidget(self.checkBoxManufacturer)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBoxResults = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxResults.sizePolicy().hasHeightForWidth())
        self.groupBoxResults.setSizePolicy(sizePolicy)
        self.groupBoxResults.setObjectName("groupBoxResults")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxResults)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxAlive = QtWidgets.QCheckBox(self.groupBoxResults)
        self.checkBoxAlive.setChecked(True)
        self.checkBoxAlive.setObjectName("checkBoxAlive")
        self.horizontalLayout_5.addWidget(self.checkBoxAlive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnClearIpList = QtWidgets.QToolButton(self.groupBoxResults)
        self.btnClearIpList.setObjectName("btnClearIpList")
        self.horizontalLayout_5.addWidget(self.btnClearIpList)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.ipList = QtWidgets.QTreeView(self.groupBoxResults)
        self.ipList.setSortingEnabled(True)
        self.ipList.setObjectName("ipList")
        self.verticalLayout.addWidget(self.ipList)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.groupBoxResults)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 526, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuClear_Scan_History = QtWidgets.QMenu(self.menuSettings)
        self.menuClear_Scan_History.setObjectName("menuClear_Scan_History")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClean_2 = QtWidgets.QAction(MainWindow)
        self.actionClean_2.setObjectName("actionClean_2")
        self.actionDist_Clean = QtWidgets.QAction(MainWindow)
        self.actionDist_Clean.setObjectName("actionDist_Clean")
        self.actionSettings_2 = QtWidgets.QAction(MainWindow)
        self.actionSettings_2.setObjectName("actionSettings_2")
        self.actionSubmit_Issue = QtWidgets.QAction(MainWindow)
        self.actionSubmit_Issue.setObjectName("actionSubmit_Issue")
        self.actionDeploy = QtWidgets.QAction(MainWindow)
        self.actionDeploy.setObjectName("actionDeploy")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionClear_Recent_Files = QtWidgets.QAction(MainWindow)
        self.actionClear_Recent_Files.setObjectName("actionClear_Recent_Files")
        self.actionSettings_3 = QtWidgets.QAction(MainWindow)
        self.actionSettings_3.setObjectName("actionSettings_3")
        self.actionSettings_4 = QtWidgets.QAction(MainWindow)
        self.actionSettings_4.setObjectName("actionSettings_4")
        self.actionServe = QtWidgets.QAction(MainWindow)
        self.actionServe.setObjectName("actionServe")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.actionScan_Range = QtWidgets.QAction(MainWindow)
        self.actionScan_Range.setObjectName("actionScan_Range")
        self.actionScan_Custom_History = QtWidgets.QAction(MainWindow)
        self.actionScan_Custom_History.setObjectName("actionScan_Custom_History")
        self.actionStart_Range_Scan = QtWidgets.QAction(MainWindow)
        self.actionStart_Range_Scan.setObjectName("actionStart_Range_Scan")
        self.actionStart_Stop_Scan = QtWidgets.QAction(MainWindow)
        self.actionStart_Stop_Scan.setObjectName("actionStart_Stop_Scan")
        self.actionStop_Scan = QtWidgets.QAction(MainWindow)
        self.actionStop_Scan.setObjectName("actionStop_Scan")
        self.actionCheck_For_Updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_For_Updates.setObjectName("actionCheck_For_Updates")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuClear_Scan_History.addAction(self.actionAll)
        self.menuClear_Scan_History.addSeparator()
        self.menuClear_Scan_History.addAction(self.actionScan_Range)
        self.menuClear_Scan_History.addAction(self.actionScan_Custom_History)
        self.menuSettings.addAction(self.menuClear_Scan_History.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionSettings_4)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionStart_Range_Scan)
        self.menuSettings.addAction(self.actionStart_Stop_Scan)
        self.menuSettings.addAction(self.actionStop_Scan)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCheck_For_Updates)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.menuBar.triggered['QAction*'].connect(MainWindow.onMenubar)
        self.spinHostTimeout.valueChanged['int'].connect(MainWindow.saveConfig)
        self.btnCustomScan.clicked.connect(MainWindow.onScanCustom)
        self.btnScan.clicked.connect(MainWindow.onScan)
        self.checkBoxAlive.toggled['bool'].connect(MainWindow.onResultsFilter)
        self.btnClearIpList.clicked.connect(MainWindow.onClearResults)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Scan Range"))
        self.startIp.setToolTip(_translate("MainWindow", "Start IP Address"))
        self.endIp.setToolTip(_translate("MainWindow", "End IP Address"))
        self.btnScan.setToolTip(_translate("MainWindow", "Start Range Scan (F5) / Stop (F7)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Custom Scan Range"))
        self.stringIp.setToolTip(_translate("MainWindow", "Scan ranges of IP addresses. Can scan multiple ranges. For example: 192.168.0.1-110, 192.168.1.5-15"))
        self.stringIp.setCurrentText(_translate("MainWindow", "192.168.0.0-255"))
        self.btnCustomScan.setToolTip(_translate("MainWindow", "Start Custom Scan (F6) / Stop (F7)"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Scan Configuration"))
        self.label.setToolTip(_translate("MainWindow", "Timeout for checking hostname (s) [-1 == 5s]"))
        self.label.setText(_translate("MainWindow", "Hostname Timeout:"))
        self.spinHostTimeout.setToolTip(_translate("MainWindow", "Timeout for checking hostname (s) [-1 == 5s]"))
        self.checkBoxHostname.setText(_translate("MainWindow", "Hostname"))
        self.checkBoxMac.setText(_translate("MainWindow", "MAC Address"))
        self.checkBoxManufacturer.setText(_translate("MainWindow", "Manufacturer"))
        self.groupBoxResults.setTitle(_translate("MainWindow", "Results"))
        self.checkBoxAlive.setText(_translate("MainWindow", "Show Alive Only"))
        self.btnClearIpList.setToolTip(_translate("MainWindow", "Clear Scan Results (Stops Scan)"))
        self.btnClearIpList.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Tools"))
        self.menuClear_Scan_History.setTitle(_translate("MainWindow", "Clear Scan History"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSettings.setText(_translate("MainWindow", "Build"))
        self.actionSettings.setShortcut(_translate("MainWindow", "F5"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionClean_2.setText(_translate("MainWindow", "Clean"))
        self.actionDist_Clean.setText(_translate("MainWindow", "Dist Clean"))
        self.actionSettings_2.setText(_translate("MainWindow", "Settings"))
        self.actionSettings_2.setShortcut(_translate("MainWindow", "F10"))
        self.actionSubmit_Issue.setText(_translate("MainWindow", "Submit Issue"))
        self.actionSubmit_Issue.setShortcut(_translate("MainWindow", "F2"))
        self.actionDeploy.setText(_translate("MainWindow", "Deploy"))
        self.actionDeploy.setShortcut(_translate("MainWindow", "F6"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setShortcut(_translate("MainWindow", "F7"))
        self.actionClear_Recent_Files.setText(_translate("MainWindow", "Clear Recent Files"))
        self.actionSettings_3.setText(_translate("MainWindow", "Settings"))
        self.actionSettings_4.setText(_translate("MainWindow", "Settings"))
        self.actionSettings_4.setShortcut(_translate("MainWindow", "F10"))
        self.actionServe.setText(_translate("MainWindow", "Serve"))
        self.actionAll.setText(_translate("MainWindow", "All"))
        self.actionScan_Range.setText(_translate("MainWindow", "Scan Range"))
        self.actionScan_Custom_History.setText(_translate("MainWindow", "Custom Scan"))
        self.actionStart_Range_Scan.setText(_translate("MainWindow", "Start Range Scan"))
        self.actionStart_Range_Scan.setToolTip(_translate("MainWindow", "Start Range Scan (F5) / Stop (F7)"))
        self.actionStart_Range_Scan.setShortcut(_translate("MainWindow", "F5"))
        self.actionStart_Stop_Scan.setText(_translate("MainWindow", "Start Custom Scan"))
        self.actionStart_Stop_Scan.setToolTip(_translate("MainWindow", "Start Custom Scan (F6) / Stop (F7)"))
        self.actionStart_Stop_Scan.setShortcut(_translate("MainWindow", "F6"))
        self.actionStop_Scan.setText(_translate("MainWindow", "Stop Scan"))
        self.actionStop_Scan.setShortcut(_translate("MainWindow", "F7"))
        self.actionCheck_For_Updates.setText(_translate("MainWindow", "Check For Updates"))

