
name: zippy-ip-scanner
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Zippy Ip Scanner # 79 char long summary
description: Zippy Ip Scanner is a free, open source IP scanning application. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  app:
    command: bin/zippy-ip-scanner
    icon: src/icon.ico
    
parts:
  my-app:
    plugin: python
    python-version: python3
    source: git://github.com/swprojects/Zippy-Ip-Scanner.git

